# Generated by Django 4.2.3 on 2023-07-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0003_alter_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='code',
            field=models.CharField(default='1da55b', editable=False, max_length=6, primary_key=True, serialize=False),
        ),
    ]
