# Generated by Django 4.2.3 on 2023-07-19 09:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('referral', '0009_alter_referral_code_alter_referral_invited_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='code',
            field=models.CharField(default='78561f', editable=False, max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='referral',
            name='invited_user',
            field=models.ManyToManyField(related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
    ]
