# Generated by Django 4.2.3 on 2023-07-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0010_alter_referral_code_alter_referral_invited_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='code',
            field=models.CharField(default='5dbf06', editable=False, max_length=6, primary_key=True, serialize=False),
        ),
    ]
